[workspace]
resolver = "2"
members = ["cmd"]

[package]
name = "newbound"
version = "0.1.0"
edition = "2021"

[features]

reload = ["dep:hot-lib-reloader","flowlang/mirror","ndata/mirror","cmd/reload"]
serde_support = ["serde","serde_json","flowlang/serde_support","ndata/serde_support","cmd/serde_support"]
java_runtime = ["flowlang/java_runtime"]
python_runtime = ["flowlang/python_runtime"]
javascript_runtime = ["flowlang/javascript_runtime"]

[dependencies]
cmd = { path = "./cmd" }
hot-lib-reloader = { version = "^0.6", optional = true }
flowlang = { version = "0.2.5" }
#flowlang = { path = "../../rust/flow" }
ndata="0.2.25"
#ndata = { path = "../../rust/ndata" }
serde = { version = "1.0.143", features = ["derive"], optional = true }
serde_json = { version = "1.0.83", optional = true }

uuid = { version="1.1.2", features=["v4"] }
x25519-dalek = "1.2.0"
zip = { version="0.6.2", features=["deflate-miniz"] }
local-ip-address = "0.4.8"
aes = "0.8.1"
walkdir = "2.3.2"
rand = "0.7"
blake2 = "0.10.4"
state = "0.5.3"

[[bin]]
name = "newbound"
path = "src/main.rs"

