[package]
name = "newbound"
version = "0.1.0"
edition = "2021"

[features]
java_runtime = ["flowlang/java_runtime"]
python_runtime = ["flowlang/python_runtime"]
javascript_runtime = ["flowlang/javascript_runtime"]

[dependencies]
flowlang = { version = "0.1.12" }
#flowlang = { path = "../../rust/flow" }
ndata="0.1.5"
#ndata = { path = "../../rust/ndata" }
state="0.5.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
jni = { version = "0.19.0" }

[[bin]]
name = "newbound"
path = "src/main.rs"

[[bin]]
name = "newboundx"
path = "src/execute.rs"

[[bin]]
name = "newboundb"
path = "src/build.rs"

[lib]
crate_type = ["lib","cdylib"]
name = "flow"
path = "src/libflowlang.rs"

