[workspace]
resolver = "2"
members = ["cmd"]

[package]
name = "newbound"
version = "0.1.0"
edition = "2021"

[features]
reload = ["dep:hot-lib-reloader"]
serde_support = ["serde","serde_json","flowlang/serde_support","ndata/serde_support","cmd/serde_support"]
java_runtime = ["flowlang/java_runtime"]
python_runtime = ["flowlang/python_runtime"]
javascript_runtime = ["flowlang/javascript_runtime"]

[dependencies]
cmd = { path = "./cmd" }
hot-lib-reloader = { version = "^0.6", optional = true }
flowlang = { version = "0.1.30" }
#flowlang = { path = "../../rust/flow" }
ndata="0.2.12"
#ndata = { path = "../../rust/ndata" }
serde = { version = "1.0.143", features = ["derive"], optional = true }
serde_json = { version = "1.0.83", optional = true }

[[bin]]
name = "newbound"
path = "src/main.rs"

