[package]
name = "newbound"
version = "0.1.0"
edition = "2021"

[dependencies]
flowlang = "0.1.5"
#flowlang = { path = "../../rust/flow" }
ndata="0.1.4"
#ndata = { path = "../../rust/ndata" }
state="0.5.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

[[bin]]
name = "newbound"
path = "src/main.rs"

[[bin]]
name = "newboundx"
path = "src/execute.rs"

[[bin]]
name = "newboundb"
path = "src/build.rs"
