[package]
name = "newbound"
version = "0.1.0"
edition = "2021"

[features]
serde_support = ["serde","serde_json","flowlang/serde_support","ndata/serde_support"]
java_runtime = ["flowlang/java_runtime"]
python_runtime = ["flowlang/python_runtime"]
javascript_runtime = ["flowlang/javascript_runtime"]

[dependencies]
flowlang = { version = "0.1.16" }
#flowlang = { path = "../../rust/flow" }
ndata="0.2.2"
#ndata = { path = "../../rust/ndata" }
state="0.5.3"
jni = { version = "0.19.0" }
serde = { version = "1.0.143", features = ["derive"], optional = true }
serde_json = { version = "1.0.83", optional = true }

[[bin]]
name = "newbound"
path = "src/main.rs"

[[bin]]
name = "newboundx"
path = "src/execute.rs"

[[bin]]
name = "newboundb"
path = "src/build.rs"

[lib]
crate_type = ["lib","cdylib"]
name = "flow"
path = "src/libflowlang.rs"

