[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[features]

serde_support = ["serde","serde_json","flowlang/serde_support","ndata/serde_support"]
reload = ["flowlang/mirror","ndata/mirror"]

[dependencies]
csv = "1.2.2"
attohttpc = "0.24.0"
flowlang = "0.2.13"
#flowlang = { path = "../../rust/flow" }
ndata="0.3.5"
#ndata = { path = "../../rust/ndata" }
serde = { version = "1.0.155", features = ["derive"], optional = true }
serde_json = { version = "1.0.94", optional = true }
