[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[features]
serde_support = ["serde","serde_json","flowlang/serde_support","ndata/serde_support"]
reload = ["flowlang/mirror","ndata/mirror"]

[dependencies]
flowlang = { version = "0.2.0" }
#flowlang = { path = "../../../rust/flow" }
ndata="0.2.25"
#ndata = { path = "../../../rust/ndata" }
serde = { version = "1.0.143", features = ["derive"], optional = true }
serde_json = { version = "1.0.83", optional = true }

#chrono = "0.4.22"
#image = "0.24.4"
#simple_moving_average = "0.1.2"
#state = "0.5.3"

