[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[features]

serde_support = ["serde","serde_json","flowlang/serde_support","ndata/serde_support"]
reload = ["flowlang/mirror","ndata/mirror"]

[dependencies]
dlib-face-recognition = { version = "0.3.1", features = ["build-native", "embed-all"] }
image = "0.24.7"
futures = "0.3.28"
serenity = { version = "0.11.5", default-features = false, features = ["builder", "cache", "client", "rustls_backend", "model", "utils", "gateway"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
attohttpc = "0.24.0"
csv = "1.2.2"
open = "3.2.0"
flowlang = "0.2.16"
ndata="0.3.6"
serde = { version = "1.0.155", features = ["derive"], optional = true }
serde_json = { version = "1.0.94", optional = true }
