use ndata::dataobject::DataObject;
use ndata::dataarray::DataArray;
pub fn execute(o: DataObject) -> DataObject {
    use std::panic;
    for p in ["repo", "message"] {
        if !o.has(p) {
            let mut e = DataObject::new();
            e.put_string("status", "err");
            e.put_string("msg", &format!("missing required parameter: {}", p));
            let mut result_obj = DataObject::new();
            result_obj.put_object("a", e);
            return result_obj;
        }
    }
    let ax = panic::catch_unwind(panic::AssertUnwindSafe(|| {
        let arg_0: String = o.get_string("repo");
        let arg_1: String = o.get_string("message");
        untrack_generated(arg_0, arg_1)
    }));
    match ax {
        Ok(ax) => {
            let mut result_obj = DataObject::new();
    result_obj.put_object("a", ax);
            result_obj
        }
        Err(err) => {
            let mut err_obj = DataObject::new();
            err_obj.put_string("status", "err");

            let msg = if let Some(s) = err.downcast_ref::<&str>() {
                s.to_string()
            } else if let Some(s) = err.downcast_ref::<String>() {
                s.clone()
            } else {
                "Unknown panic occurred".to_string()
            };

            err_obj.put_string("msg", &msg);
            // Wrapped in the same `a` envelope a successful return uses.
            // Unwrapped, callers that unpack the envelope (newbound's
            // format_result, for one) report an opaque 500 — "Not an object:
            // DString(\"err\")" — instead of this message.
            let mut result_obj = DataObject::new();
            result_obj.put_object("a", err_obj);
            result_obj
        }
    }
}

pub fn untrack_generated(repo: String, message: String) -> DataObject {
// Library repos never track builder-generated files. <crate>/src/api.rs is
// regenerated by every rebuild to mirror whatever libraries THIS box has, and
// <crate>/Cargo.lock resolves THIS box's dependency tree - shipping either makes
// every other instance's checkout dirty after its first build, and whichever
// side wins a merge is wrong somewhere. This makes a repo conform: rm --cached
// every tracked Cargo.lock and src/api.rs (the files stay on disk), add an
// anchored ignore line for each crate's pair (a crate = a directory holding a
// tracked Cargo.toml, the root included) that is not already ignored, commit,
// push when the branch tracks a remote. Idempotent: a conforming repo is an ok
// no-op. Refuses canon (its workspace Cargo.lock is tracked on purpose), the
// default branch (branches always), a merge in flight, and a non-empty index
// (pre-staged work would ride into the commit).
fn fail(msg: &str) -> DataObject {
    let mut o = DataObject::new();
    o.put_string("status", "err");
    o.put_string("msg", msg);
    o
}
fn sargs(v: &[&str]) -> DataArray {
    let mut a = DataArray::new();
    for s in v { a.push_string(s); }
    a
}
fn okr(r: &DataObject) -> bool { r.try_get_string("status").unwrap_or_default() == "ok" }
fn outs(r: &DataObject) -> String { r.try_get_string("out").unwrap_or_default() }
fn errs(r: &DataObject) -> String {
    let e = r.try_get_string("err").unwrap_or_default().trim().to_string();
    if e.is_empty() { r.try_get_string("msg").unwrap_or_default() } else { e }
}
fn ref_exists(repo: &str, r: &str) -> bool {
    let x = crate::dev::git::read::read(repo.to_string(), "rev-parse".to_string(), sargs(&["--verify", "--quiet", r]));
    okr(&x) && !outs(&x).trim().is_empty()
}
fn generated(p: &str) -> bool {
    p == "Cargo.lock" || p.ends_with("/Cargo.lock") || p == "src/api.rs" || p.ends_with("/src/api.rs")
}

let repo = repo.trim().to_string();
let mut steps = DataArray::new();

// registry: role and path
let reg = crate::dev::git::repos::repos();
if !okr(&reg) { return fail(&errs(&reg)); }
let repos = reg.get_object("repos");
if !repos.has(&repo) { return fail(&format!("unknown repo '{}'", repo)); }
let entry = repos.get_object(&repo);
let role = entry.try_get_string("role").unwrap_or_default();
let path = entry.try_get_string("path").unwrap_or_default();
if role == "canon" { return fail("canon tracks its workspace Cargo.lock on purpose - this is for library repos"); }
if path.is_empty() { return fail("registry entry has no path"); }

let st = crate::dev::git::read::read(repo.clone(), "status".to_string(), sargs(&["--porcelain=v2", "--branch"]));
if !okr(&st) { return fail(&format!("status failed: {}", errs(&st))); }
let mut cur = String::new();
let mut upstream = String::new();
let mut conflicts = 0i64;
for line in outs(&st).lines() {
    if let Some(h) = line.strip_prefix("# branch.head ") { cur = h.trim().to_string(); }
    else if let Some(u) = line.strip_prefix("# branch.upstream ") { upstream = u.trim().to_string(); }
    else if line.starts_with("u ") { conflicts += 1; }
}
if ref_exists(&repo, "MERGE_HEAD") { return fail("a merge is in progress - finish it (commit) or abort it (merge --abort) first"); }
if conflicts > 0 { return fail(&format!("{} conflicted path(s) - resolve them first", conflicts)); }
if cur == "master" || cur == "main" || cur == "(detached)" || cur.is_empty() {
    return fail(&format!("on '{}' - this commits, and work belongs on a branch (start_branch, or carry_branch when {} holds commits origin lacks)", cur, cur));
}
let staged = crate::dev::git::read::read(repo.clone(), "diff".to_string(), sargs(&["--cached", "--quiet"]));
if !okr(&staged) { return fail("the index holds staged changes - commit or unstage them first, so only this change lands in the commit"); }

// what is tracked that should not be, and which crates exist
let ls = crate::dev::git::read::read(repo.clone(), "ls-files".to_string(), sargs(&["--", "*Cargo.lock", "*api.rs", "*Cargo.toml"]));
if !okr(&ls) { return fail(&format!("ls-files failed: {}", errs(&ls))); }
let mut tracked: Vec<String> = Vec::new();
let mut crates: Vec<String> = Vec::new();
for l in outs(&ls).lines() {
    let p = l.trim();
    if p.is_empty() { continue; }
    if generated(p) { tracked.push(p.to_string()); }
    else if p == "Cargo.toml" { crates.push(String::new()); }
    else if let Some(d) = p.strip_suffix("/Cargo.toml") { crates.push(d.to_string()); }
}
tracked.sort();
crates.sort();

let mut untracked = DataArray::new();
if !tracked.is_empty() {
    let mut a: Vec<&str> = vec!["--cached", "--quiet", "--"];
    for p in &tracked { a.push(p.as_str()); }
    let r = crate::dev::git::write::write(repo.clone(), "rm".to_string(), sargs(&a));
    if !okr(&r) { return fail(&format!("rm --cached failed: {} - nothing changed", errs(&r))); }
    steps.push_string(&format!("rm --cached {}", tracked.join(" ")));
    for p in &tracked { untracked.push_string(p); }
}

// ignore lines for every crate's pair that git does not already ignore
// (check-ignore ignores tracked files by default, hence after rm --cached)
let mut lines: Vec<String> = Vec::new();
for d in &crates {
    for f in ["Cargo.lock", "src/api.rs"] {
        let p = if d.is_empty() { f.to_string() } else { format!("{}/{}", d, f) };
        let c = crate::dev::git::read::read(repo.clone(), "check-ignore".to_string(), sargs(&["-q", "--", &p]));
        if !okr(&c) { lines.push(format!("/{}", p)); }
    }
}
let mut added = DataArray::new();
if !lines.is_empty() {
    let gi = std::path::Path::new(&path).join(".gitignore");
    let mut text = std::fs::read_to_string(&gi).unwrap_or_default();
    if !text.is_empty() && !text.ends_with('\n') { text.push('\n'); }
    text.push_str("# builder-generated per instance, never tracked (dev.git.untrack_generated)\n");
    for l in &lines { text.push_str(l); text.push('\n'); added.push_string(l); }
    if let Err(e) = std::fs::write(&gi, text) { return fail(&format!("could not write .gitignore: {}", e)); }
    let r = crate::dev::git::write::write(repo.clone(), "add".to_string(), sargs(&["--", ".gitignore"]));
    if !okr(&r) { return fail(&format!("add .gitignore failed: {}", errs(&r))); }
    steps.push_string(&format!(".gitignore += {}", lines.join(" ")));
}

let mut o = DataObject::new();
o.put_string("status", "ok");
o.put_string("branch", &cur);
o.put_array("untracked", untracked);
o.put_array("ignored", added);
if tracked.is_empty() && lines.is_empty() {
    o.put_boolean("committed", false);
    o.put_boolean("pushed", false);
    o.put_array("steps", steps);
    o.put_string("msg", "already conforms - no generated api.rs or Cargo.lock tracked, every crate's pair ignored");
    return o;
}
let msg = if message.trim().is_empty() { "untrack builder-generated api.rs and Cargo.lock; ignore them per crate".to_string() } else { message.trim().to_string() };
let r = crate::dev::git::write::write(repo.clone(), "commit".to_string(), sargs(&["-m", &msg]));
if !okr(&r) { return fail(&format!("commit failed: {} - the index holds the change; commit it by hand", errs(&r))); }
steps.push_string("commit");
let mut pushed = false;
let mut push_err = String::new();
if !upstream.is_empty() {
    let p = crate::dev::git::remote_op::remote_op(repo.clone(), "push".to_string(), sargs(&[]));
    pushed = okr(&p);
    if pushed { steps.push_string("push"); } else { push_err = errs(&p); }
}
o.put_boolean("committed", true);
o.put_boolean("pushed", pushed);
o.put_string("push_err", &push_err);
o.put_array("steps", steps);
o.put_string("msg", &format!("untracked {} file(s), ignored {} path(s), committed on {}{}",
    tracked.len(), lines.len(), cur,
    if pushed { ", pushed" } else if upstream.is_empty() { " (branch is unpublished)" } else { " - push failed" }));
o
}
